### ISSUE TITLE
Hi Fiends 

### ISSUE THREAD

**Issue by rohi0007** [pranoyr/large-scale-visual-relationship-understanding#2]
After trained the model successfully. When I am trying to test using inference.py it download a model from github and successfully working, but for the same we using our trained model from the snapshot folder it giving me an error.

Word Embeddings loaded.
Wiki words converted to lowercase.
Model Restored
Traceback (most recent call last):
  File "inference.py", line 81, in <module>
    detections, losses = faster_rcnn([im])
  File "/home/rohitml/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/rohitml/large-scale-visual-relationship-understanding/modelling/model.py", line 99, in forward
    fpn_feature_maps, proposals, images.image_sizes)
  File "/home/rohitml/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/rohitml/large-scale-visual-relationship-understanding/modelling/roi_head.py", line 506, in forward
    _, sbj_indices = torch.max(sbj_cls_scores_list[i], dim=1)
RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity

can you please help on this.

**Comment by pranoyr** [comment]
May be due to no predictions during inference.
